version: '3.8'

services:
  odoo_db:
    image: postgres:15
    container_name: odoo_postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo_admin_2026
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - odoo-network

  odoo:
    image: odoo:17.0
    container_name: odoo_community
    depends_on:
      - odoo_db
    ports:
      - "8069:8069"
      - "8072:8072"  # For live chat
    environment:
      - HOST=odoo_db
      - USER=odoo
      - PASSWORD=odoo_admin_2026
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config/odoo:/etc/odoo
      - ./addons:/mnt/extra-addons
    restart: unless-stopped
    networks:
      - odoo-network
    command: --
      --dev=reload
      --limit-time-cpu=600
      --limit-time-real=1200
      --workers=0

volumes:
  odoo-db-data:
    driver: local
  odoo-web-data:
    driver: local

networks:
  odoo-network:
    driver: bridge
